rootDomain: k8s-nightly.epm.kharlamov.biz
domainDelimiter: "-"
namespace: default
enclaveName: unknown
localDomain: "cluster.local"
addLocalDomain: false
clusterName: ""

log_level: info

auth:
  enabled: false
  annotations: {}

feedback:
  replicas: 1
  ingress:
    annotations: {}
    domain:
      partial: feedback
    tls:
      enabled: true
      autoSecretNameDeduction: true

  image:
    repository: "legion/k8s-fluentd"
    tag: "latest"
    pullPolicy: "Always"

  s3:
    bucket: "none"
    region: "none"

    time_slice_format: "%Y%m%d%H"
    time_slice_wait: "5m"

    store_as: "json"

    buffering:
      timekey: 1m       # chunks length (window size)
      timekey_wait: 0s  # delay for flush (after end of window)
      path: /tmp

    format: "json"
    include_time_key: "true"
    time_key: "time"

edi:
  enabled: true
  replicas: 1
  image:
    repository: "legion/edi"
    tag: "latest"
    pullPolicy: "Always"

  rbac: true

  k8s_api_retry_number_max_limit: 10
  k8s_api_retry_delay_sec: 3

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: edi
    tls:
      enabled: true
      autoSecretNameDeduction: true


edge:
  enabled: true
  replicas: 2
  enableHomePage: true
  image:
    repository: "legion/k8s-edge"
    tag: "latest"
    pullPolicy: "Always"

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: edge
    tls:
      enabled: true
      autoSecretNameDeduction: true

jenkins:
  enabled: true
  image:
    repository: "legion/k8s-jenkins"
    tag: "latest"
    pullPolicy: "Always"

  rbac: true

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: jenkins
    tls:
      enabled: true
      autoSecretNameDeduction: true

  git_secret_name: false

  airflow:
    enabled: false
    rest_url: ''
    s3_url: ''
    expected_output: ''

    dags_volume_pvc: ''

graphite:
  enabled: true
  image:
    repository: "hopsoft/graphite-statsd"
    tag: "v0.9.15-phusion0.9.18"
    pullPolicy: "Always"


grafana:
  enabled: true
  image:
    repository: "legion/k8s-grafana"
    tag: "latest"
    pullPolicy: "Always"

  # graphite: "aaaa"

  ingress:
    enabled: true
    annotations: {}
    domain:
      partial: grafana
    tls:
      enabled: true
      autoSecretNameDeduction: true

connections:
  docker:
    type: proxy
    url: ~
    user: ~
    password: ~

secrets:
  nexus:
    admin: "jonny"
  token_ttl_minutes: "120"
  token_exp_datetime: ~