---
####################
# Create Kubernetes cluster using Kops
####################

- name: Create kops configuration
  template:
    src: kops.yaml.j2
    dest: "{{ tmp_dir }}/kops.{{ cluster_name }}.yaml"
    mode: 0644

- name: Configure the cluster
  shell: "{{ kops_path }} create -f {{ tmp_dir }}/kops.{{ cluster_name }}.yaml --state {{ state_store }}"

- name: Configure ssh key
  shell: "{{ kops_path }} create secret --name {{ cluster_name }} sshpublickey admin -i  {{ ssh_public_key }} --state {{ state_store }}"

- name: Create the physical cluster
  shell: "{{ kops_path }} update cluster {{ cluster_name }} --yes --state {{ state_store }}"

- name: Verify that all Kubernetes nodes are ready
  shell: kubectl --context {{ cluster_name }} get nodes | grep master | wc -l
  register: cmd_result
  until: cmd_result.stdout == "{{ k8s_master_zones|length }}"
  retries: 20
  delay: 60
